# Generated by Django 5.0.1 on 2024-07-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
